# openapi.yaml
openapi: 3.1.0
info:
  title: Enkrypt Backend API
  version: 1.0.0
paths:
  /get:
    get:
      operationId: GetRoot
      responses:
        200:
          $ref: '#/components/responses/GetRootSuccess'

  /version:
    get:
      operationId: GetVersion
      responses:
        200:
          $ref: '#/components/responses/GetVersionSuccess'

  /health:
    get:
      operationId: GetHealth
      responses:
        200:
          $ref: '#/components/responses/GetHealthSuccess'

  /schema:
    get:
      operationId: GetSchema
      responses:
        200:
          $ref: '#/components/responses/GetSchemaSuccess'

  /backups/{publicKey}:
    get:
      operationId: GetUserBackups
      parameters:
        - $ref: '#/components/parameters/PublicKey'
      responses:
        200:
          $ref: '#/components/responses/GetUserBackupsSuccess'

  /backups/{publicKey}/{userId}:
    post:
      operationId: PostUserBackup
      parameters:
        - $ref: '#/components/parameters/PublicKey'
        - $ref: '#/components/parameters/UserId'
      requestBody:
        $ref: '#/components/requestBodies/PostUserBackup'
      responses:
        200:
          $ref: '#/components/responses/PostUserBackupSuccess'

components:
  parameters:
    PublicKey:
      name: publicKey
      in: path
      # required: true # OpenAPI 3.0 property not compatible with JSON schema
      schema:
        $ref: '#/components/schemas/PublicKey'

    UserId:
      name: userId
      in: path
      # required: true # OpenAPI 3.0 property not compatible with JSON schema
      schema:
        $ref: '#/components/schemas/UserId'

  requestBodies:
    PostUserBackup:
      description: hi!
      content:
        application/json:
          $ref: '#/components/schemas/PostUserBackupRequest'

  responses:
    GetRootSuccess:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetRootResponse'

    GetVersionSuccess:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetVersionResponse'

    GetHealthSuccess:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetHealthResponse'

    GetSchemaSuccess:
      content:
        application/yaml:
          schema:
            $ref: '#/components/schemas/GetSchemaResponse'

    GetUserBackupsSuccess:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetUserBackupsResponse'

    PostUserBackupSuccess:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PostUserBackupResponse'

  schemas:
    ByteString:
      type: string
      pattern: ^0x([0-9a-fA-F]{2})*$
    Bytes32:
      type: string
      pattern: ^0x[0-9a-fA-F]{64}$
    Bytes64:
      type: string
      pattern: ^0x[0-9a-fA-F]{128}$
    Hex:
      type: string
      pattern: ^0x[0-9a-fA-F]*$
    UUID:
      type: string
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
    PublicKey:
      $ref: '#/components/schemas/Bytes64'
    UserId:
      $ref: '#/components/schemas/UUID'

    GetRootResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    GetHealthResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    GetVersionResponse:
      type: object
      required:
        - version
      properties:
        version:
          type: string

    GetSchemaResponse:
      type: string

    PostUserBackupRequest:
      type: object
      required:
        - signature
        - payload
      properties:
        signature:
          $ref: '#/components/schemas/ByteString'
        payload:
          $ref: '#/components/schemas/ByteString'

    PostUserBackupResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    GetUserBackupsResponse:
      type: object
      required:
        - backups
      properties:
        backups:
          type: array
          items:
            $ref: '#/components/schemas/Backup'

    Backup:
      type: object
      required:
        - updatedAt
        - userId
        - payload
      properties:
        updatedAt:
          type: string
          format: date-time
        userId:
          type: string
        payload:
          $ref: '#/components/schemas/ByteString'
